/* tslint:disable */
/* eslint-disable */
import {AuthenticationResponseRolesEnum} from "./authentication-response.ts";

/**
 * Club Management API
 * Club Management API
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is NOT auto generated by the swagger code generator program.
 * YOU can edit the class manually.
 */

export interface AuthenticationUser{
    /**
     *
     * @type {number}
     * @memberof AuthenticationUser
     */
    id?: number
    /**
     *
     * @type {Array<string>}
     * @memberof AuthenticationUser
     */
    roles?: Array<AuthenticationResponseRolesEnum>;

}

