/* tslint:disable */
/* eslint-disable */
/**
 * Club Management API
 * Club Management API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {

} from ".";

/**
 * 
 *
 * @export
 * @interface Budget
 */
export interface Budget {

    /**
     * @type {number}
     * @memberof Budget
     */
    idBudget?: number;

    /**
     * @type {number}
     * @memberof Budget
     */
    budgetInitial?: number;

    /**
     * @type {number}
     * @memberof Budget
     */
    usedBudget?: number;

    /**
     * @type {string}
     * @memberof Budget
     */
    budgetType?: BudgetBudgetTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum BudgetBudgetTypeEnum {
    _1 = 'TYPE_1',
    _2 = 'TYPE_2'
}

