/* tslint:disable */
/* eslint-disable */
/**
 * Club Management API
 * Club Management API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ClubIdMembersBody
 */
export interface ClubIdMembersBody {
    /**
     * 
     * @type {Blob}
     * @memberof ClubIdMembersBody
     */
    file: Blob;
}
