/* tslint:disable */
/* eslint-disable */
/**
 * Club Management API
 * Club Management API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import {
    Club,
} from ".";

/**
 * 
 *
 * @export
 * @interface Event
 */
export interface Event {

    /**
     * @type {number}
     * @memberof Event
     */
    idEvent?: number;

    /**
     * @type {string}
     * @memberof Event
     */
    name?: string;

    /**
     * @type {string}
     * @memberof Event
     */
    description?: string;

    /**
     * @type {Club}
     * @memberof Event
     */
    organisateur?: Club;

    /**
     * @type {Date}
     * @memberof Event
     */
    date?: Date;

    /**
     * @type {string}
     * @memberof Event
     */
    cover?: string;

    /**
     * @type {string}
     * @memberof Event
     */
    status?: EventStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum EventStatusEnum {
    REQUESTED = 'REQUESTED',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    POSTEVENT = 'POST_EVENT',
    CLOSED = 'CLOSED'
}

