/* tslint:disable */
/* eslint-disable */
/**
 * Club Management API
 * Club Management API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NewClubDetailsRequest
 */
export interface NewClubDetailsRequest {
    /**
     * 
     * @type {string}
     * @memberof NewClubDetailsRequest
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof NewClubDetailsRequest
     */
    cover?: string;
    /**
     * 
     * @type {string}
     * @memberof NewClubDetailsRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof NewClubDetailsRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof NewClubDetailsRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof NewClubDetailsRequest
     */
    aboutUs?: string;
}
