/* tslint:disable */
/* eslint-disable */
/**
 * Club Management API
 * Club Management API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface Personnel
 */
export interface Personnel {

    /**
     * @type {number}
     * @memberof Personnel
     */
    idA?: number;

    /**
     * @type {string}
     * @memberof Personnel
     */
    lastName?: string;

    /**
     * @type {string}
     * @memberof Personnel
     */
    firstName?: string;

    /**
     * @type {string}
     * @memberof Personnel
     */
    email?: string;

    /**
     * @type {Array<string>}
     * @memberof Personnel
     */
    roles?: Array<PersonnelRolesEnum>;
}

/**
 * @export
 * @enum {string}
 */
export enum PersonnelRolesEnum {
    ADMIN = 'ADMIN',
    PROF = 'PROF',
    PRESIDENT = 'PRESIDENT',
    VICEPRESIDENT = 'VICE_PRESIDENT',
    TREASURER = 'TREASURER',
    SECRETARY = 'SECRETARY',
    STUDENT = 'STUDENT'
}

