/* tslint:disable */
/* eslint-disable */
/**
 * Club Management API
 * Club Management API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface SrcClubIdBody
 */
export interface SrcClubIdBody {

    /**
     * @type {Blob}
     * @memberof SrcClubIdBody
     */
    file: Blob;
}
