/* tslint:disable */
/* eslint-disable */
/**
 * Club Management API
 * Club Management API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Student
 */
export interface Student {
    /**
     * 
     * @type {number}
     * @memberof Student
     */
    idA?: number;
    /**
     * 
     * @type {string}
     * @memberof Student
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof Student
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof Student
     */
    email?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Student
     */
    roles?: Array<StudentRolesEnum>;
    /**
     * 
     * @type {number}
     * @memberof Student
     */
    studentId?: number;
    /**
     * 
     * @type {string}
     * @memberof Student
     */
    major?: string;
    /**
     * 
     * @type {number}
     * @memberof Student
     */
    level?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum StudentRolesEnum {
    ADMIN = 'ADMIN',
    PROF = 'PROF',
    PRESIDENT = 'PRESIDENT',
    VICEPRESIDENT = 'VICE_PRESIDENT',
    TREASURER = 'TREASURER',
    SECRETARY = 'SECRETARY',
    STUDENT = 'STUDENT'
}

